### ISSUE TITLE
Should we use _utility_registrations as well?

### ISSUE THREAD

**Issue by idgserpro** [collective/collective.migrationhelpers#1]
Inspired by 
https://github.com/collective/collective.migrationhelpers/blob/c634fd18de4c5c0541f21a2bd20f89fbdc1c078b/src/collective/migrationhelpers/persistent.py#L26 and a bunch of other scripts, I used transmogrifier to migrate a website and needed to remove some utilities.

I just had a problem with a migration having the following tracebak:

```
Module ZODB.serialize, line 431, in _dump
PicklingError: Can't pickle <class 'collective.blueprint.usersandgroups.blueprint.CreateGroup'>: import of module collective.blueprint.usersandgroups.blueprint failed 
```

In the end, I needed to use `_utility_registrations`, inspired by https://github.com/4teamwork/ftw.upgrade/blob/53260eace422229070b52f5d8b1482f37a7ee18e/ftw/upgrade/step.py#L403.

Do you have more information about this issue? Would it be a nice addition here?

**Comment by pbauer** [comment]
I like the idea. We could either pass a list if Interfaces or iterate over ```adapters[0][ILocalBrowserLayerType]``` and remove anything that is a broken instance. Feel free to make a pull-request

**Comment by mauritsvanrees** [comment]
Current master branch already cleans up `_utility_registrations`. I have just now created PR #10 to cleanup `_adapter_registrations` as well.
